# !!NOTE!!
# If any of the image names or python versions change, update bors.toml

pep517_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  container:
    image: python:3

  install_script:
    - pip install --upgrade-strategy eager -U pep517

  script:
    - python3 -m pep517.check .


build_task:
  container:
    image: duckinator/bork
  setup_script:
    - git fetch --tags
  script:
    - bork build
  dist_artifacts:
    path: "dist/**"


task:
  name: "Linux $IMAGE"
  alias: Tests
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  allow_failures: $IMAGE =~ '.*[-:]rc-.*'
  env:
    matrix:
      - IMAGE: python:3.9-slim
      - IMAGE: python:rc-slim
      - IMAGE: python:3.10-slim
      - IMAGE: python:3.11-slim
      - IMAGE: python:3.12-slim

  container:
    image: $IMAGE

  depends_on:
    - build

  install_script:
    - >-
      if command -v pypy3 >/dev/null || python3 -c 'import sys; exit(sys.implementation.version.releaselevel == "final")'; then
        apt update || true;
        apt install -qq -y pkgconf libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev libsmpeg-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev libfreetype6-dev gcc
      fi
    - pip install --upgrade-strategy eager -U -r requirements-tests.txt
    - >-
      if command -v pypy3 >/dev/null; then
        pypy3 .ci/install-wheels.py
      else
        python .ci/install-wheels.py
      fi
    - >-
      apt-get update || true;
      apt-get install -qq -y libsdl2-2.0-0 libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-gfx-1.0-0 libsdl2-ttf-2.0-0

  script:
    - command -v pypy3 >/dev/null && export PY=pypy3
    - ${PY-python3} --version
    - pip list
    - pytest

  use_compute_credits: $CIRRUS_BRANCH == 'staging'


macOS_task:
  alias: Tests
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  env:
    PATH: ${HOME}/.pyenv/shims:${PATH}
    matrix:
      # To update: check the output of the most recent macOS_version job
      - PYTHON: 3.9
      - PYTHON: 3.10
      - PYTHON: 3.11
      - PYTHON: 3.12
  depends_on:
    - build
  install_script:
    # Per the pyenv homebrew recommendations.
    # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
    # - xcode-select --install  # Unnecessary on Cirrus
    - brew update    
    - brew install openssl readline sqlite3 xz zlib pyenv
    - pyenv install ${PYTHON}
    - pyenv global ${PYTHON}
    - pyenv rehash
    - pip install --upgrade-strategy eager -U -r requirements-tests.txt
    - python .ci/install-wheels.py

  script:
    - python3 --version
    - pip list
    - pytest


macOS_version_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  osx_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  install_script:
    # Per the pyenv homebrew recommendations.
    # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
    - brew install openssl readline pyenv

  script:
    - pyenv install --list


task:
  name: "Windows $IMAGE"
  alias: Tests
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  allow_failures: $IMAGE =~ '.*[-:]rc-.*'
  windows_container:
    os_version: 2019
    image: $IMAGE

  env:
    matrix:
      - IMAGE: python:3.9-windowsservercore
      - IMAGE: python:3.10-windowsservercore
      - IMAGE: python:3.11-windowsservercore
      - IMAGE: python:3.12-windowsservercore
      - IMAGE: python:rc-windowsservercore

  install_script:
    - C:\Python\python.exe -m pip install --upgrade-strategy eager -U -r requirements-tests.txt
    - C:\Python\python.exe .ci/install-wheels.py

  script:
    - C:\Python\python.exe --version
    - C:\Python\python.exe -m pip list
    - C:\Python\python.exe -m pytest


upload_task:
  only_if: $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_RELEASE != ''
  depends_on:
    - build
    # - docs
    - pep517
    - Tests
  env:
    # Encrypt at https://cirrus-ci.com/settings/repository/5170617228460032
    # https://test.pypi.org/manage/account/token/
    TWINE_TEST_TOKEN: "ENCRYPTED[0b51bffd26202987a4720bb9f1d75a9c754aa956520e23157b0bc7ae23730adde6496319e285ff205f1642aa4a17e371]"
    # https://pypi.org/manage/account/token/
    TWINE_PROD_TOKEN: "ENCRYPTED[e0de21037aee83a1a486ceeb228722831abf7ad26619c8b414d41c2c0f86340814e79691e48b09ee96b2834199b96e15]"
    # https://github.com/settings/tokens
    GITHUB_TOKEN: "ENCRYPTED[456d4343a400793d742afe6d1a3233241832276ef3eabc260d6f3923b3449d7b13b5bd8532722b3a9ab9d13862d58e34]"

  container:
    image: xonsh/xonsh:slim

  install_script:
    - pip install twine

  script:
    - xonsh .ci/upload.xsh

  examples_artifacts:
    path: "examples.zip"
